# Dockerfile jupyter - Punto-5

FROM jupyter/scipy-notebook:a374cab4fcb6

WORKDIR /notebook

VOLUME /notebook

ENV JUPYTER_TOKEN=jupyter_token

ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt




